language: python
python:
- 2.7

notifications:
  email: false

deploy:
  provider: s3
  bucket: www.glueviz.org
  skip_cleanup: true
  local-dir: test/
  upload-dir: test/

  access_key_id: AKIAI2ERWDHLW3W24X3A
  secret_access_key: $AWS_SECRET_KEY_ID
  on:
     condition:
       - "$TRAVIS_SECURE_ENV_VARS = true"
